### ISSUE TITLE
find not implemented

### ISSUE THREAD

**Issue by tW4r** [andraemon/SystemNameCalculator#2]
Impressive work!

I see that the `find` command is not implemented yet

I tried implementing it using pure brute-force for the seed, but the search space is very large: `0xFFF ^ 3 + 0x2FF` just for the Euclid galaxy

Thus it appears a more thought out solution might be needed, after looking at the code, I have noticed (please correct me if I'm wrong) that the first letter of the name is only set from the Alphaset dictionary once and never modified, only the remaining letters are modified. Thus I think it should be possible given a name extract only initial indexes on alphaset based on the first letter, and thus limit the search space vastly.

What do you think?

**Comment by andraemon** [comment]
I ended up semi-bruteforcing it by looking to see if each seed fit within the required ranges after each seed update, but search time still goes up exponentially with name length and it can take up to around 15-20 minutes to search all seeds in a galaxy (which is understandably disappointing if you've waited 20 minutes only to be told your requested name can't be found). There are some failsafes in place to prevent the program from searching for impossible/unsupported name formats, but sometimes a name just won't appear in a galaxy. 

I was looking at implementing some sort of algorithm which walked backwards along the seed update path from the narrowest seed range, but this is harder than it sounds, and at this point I've moved on to other projects. I'll probably revisit this at some point, but for now no progress is being made.
